pages:
  stage: build
  image: alpine
  script:
    - apk update && apk add asciidoc findutils gzip
    - python ./waf configure --prefix=`pwd`/public/ build install
    - find public -type f -iregex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -execdir gzip -f --keep {} \;
  artifacts:
    paths:
       - public
  tags:
    - gitlab-org
